"""
Extended keyword patches for new adversarial test phrasings.
router loads this automatically.
"""
EXTENDED_KEYWORDS = {
    "Major Depressive Episode":         ["no reason to get up","body won't cooperate","no will to move"],
    "Persistent Depressive Disorder":   ["grey zone","don't remember feeling normal","been this way so long"],
    "Anhedonia":                         ["don't do anything for me anymore","feel hollow","feels like a chore","lost its appeal","feel promoted but hollow","nothing feels rewarding"],
    "Hopelessness":                      ["can't see it getting better","future doesn't exist","can't imagine a better version"],
    "Psychomotor Retardation":          ["lifting my arm","thoughts come out slow","even typing feels heavy"],
    "Cognitive Impairment (Depression)":["couldn't track the conversation","simple decisions paralyze","couldn't follow what was said"],
    "Somatic Depression":               ["every test comes back normal","making it up","fatigued but tests show nothing"],
    "Atypical Depression":              ["came crashing back","can't stop sleeping","good briefly then crashes"],
    "Melancholic Depression":           ["first thought is dread","nothing shifts it","dread is the first thing each morning"],
    "Agitated Depression":              ["need to keep moving but nowhere","restlessness and sadness together","nowhere to put the sadness"],
    "Seasonal Affective Disorder":      ["like clockwork every year","every october","every february"],
    "Postpartum Depression":            ["feel nothing when i hold","thought there'd be a rush","no bond with my baby"],
    "Grief-Related Depression":         ["sit in his chair","eight months and still not","stop functioning after the loss"],
    "Existential Depression":           ["successful by every measure","none of it means anything","least alive i've felt"],
    "Masked Depression":                ["funny one in every room","alone at midnight","what i look like when alone"],
    "Treatment-Resistant Depression":   ["four different antidepressants","cbt dbt","complex case psychiatrist"],
    "Self-Loathing":                    ["every compliment i dismiss","own harshest prison","hold onto mistakes for years"],
    "Emotional Numbness":               ["permanently broken in me","felt nothing at all","something is broken inside","none of it reaches me"],
    "Suicidal Ideation (Passive)":      ["press a button and not exist","wishing i could not exist","not exist for a while"],
    "Suicidal Ideation (Active)":       ["researching methods","have a date in mind","don't want to be stopped"],
    "Generalized Anxiety Disorder":     ["engine that never turns off","what could go wrong next week","mind never stops"],
    "Social Anxiety":                   ["draft texts for twenty minutes","replay conversations for days","people exhaust me"],
    "Panic Attack":                     ["vision went spotty","couldn't feel my hands","heart was stopping","vision blurred suddenly"],
    "Anticipatory Anxiety":             ["already losing sleep over it","three weeks away and already","rehearsed so many times i dread"],
    "Health Anxiety":                   ["reading case studies online","convinced it's lymphoma","small lump convinced i'm ill"],
    "Separation Anxiety":               ["track his phone constantly","can't eat before he leaves","husband travels and i panic"],
    "Performance Anxiety":              ["voice started shaking","dread every presentation now","public speaker but now dread it"],
    "Agoraphobia":                      ["ordered groceries online","chest close up in crowds","third month avoiding shops"],
    "Intrusive Thoughts":               ["image of pushing","terrifies me about myself","thoughts i'd never act on"],
    "Rumination":                       ["lives rent-free in my head","hundred versions of what i should","rent-free"],
    "Hypervigilance":                   ["sleep with the lights on","check the door four times","heart slam at every sound"],
    "Catastrophizing":                  ["convinced it was meningitis","child had a fever and i panicked","every symptom becomes catastrophe"],
    "Existential Anxiety":              ["rock hurtling through space","randomness paralyzes me","hurtling through empty space"],
    "Financial Anxiety":                ["check my balance three times a day","spreadsheet for every expense","losing job makes me sick"],
    "Relationship Anxiety":             ["planned the entire breakup","six hours to reply and i spiralled","started grieving before they left"],
    "Therapy Disengagement":            ["talked in circles","what's the point of coming back","don't feel understood here"],
    "Session Dropout Risk":             ["sitting in my car outside the clinic","rescheduled three times","can't make myself walk in"],
    "Low Motivation to Continue":       ["when the moment comes i'd rather","rather scroll my phone","scroll instead of trying"],
    "Therapeutic Alliance Rupture":     ["made me feel pathetic","don't think she actually gets","said something that hurt"],
    "Skill Practice Avoidance":         ["grounding exercise feels silly","naming five things i can see","technique feels pointless"],
    "Homework Non-Compliance":          ["thought records every evening","dismiss the reminder every night","dismiss it every night"],
    "Ambivalence About Treatment":      ["paying to complain to a stranger","only thing keeping me afloat","some days it helps some days"],
    "Passive Resistance":               ["i'll say fine","say sort of","can't engage today"],
    "Information Overload Fatigue":     ["three new frameworks","window of tolerance","barely remember my name now"],
    "Digital Therapy Burnout":          ["stare at my own face on screen","feel sterile","miss being in a room with another human"],
    "Stigma-Related Withdrawal":        ["devastated if she knew i was in therapy","carry your problems yourself","planning to stop because of stigma"],
    "Logistical Barriers":              ["rotating shifts","costs more than the benefit","rearranged everything and it costs"],
    "Loss of Hope in Treatment":        ["not worse but not better","accept that this is just who i am","three years in therapy no change"],
    "Premature Termination Risk":       ["two good weeks in a row","wonder if i still need to keep coming","good weeks so i might stop"],
    "Re-Engagement Opportunity":        ["dropped out","wondering if you'd","take me back as","life got complicated so i stopped","want to restart sessions"],
    "Acute Stress Reaction":            ["hands still trembling","can't stop seeing it","an hour ago it happened","daughter told me she's been","barely holding myself together"],
    "PTSD Flashback":                   ["smell of diesel","not in my kitchen i'm back there","back there in seconds","triggers me instantly"],
    "Complex Trauma":                   ["wasn't one big event","years of small cruelties","nervous system never settled"],
    "Emotional Dysregulation":          ["dish in the sink and i screamed","cried for an hour after","scale my reactions","screamed over something tiny"],
    "Dissociation":                     ["going somewhere else in meetings","watching from the corner of the ceiling","body is in the chair but i'm not"],
    "Shame Response":                   ["never told anyone what happened","shame feels permanent","convinced it was my fault so ashamed"],
    "Guilt Response":                   ["accident happened because i was driving","friend was in the passenger seat","i was driving when it happened"],
    "Betrayal Trauma":                  ["therapist shared something i told her","can't imagine trusting a professional again","confidentiality broken"],
    "Abandonment Fear":                 ["text back quickly","i spiral when","apologize constantly","keep people close so they won't leave","spiral when no reply"],
    "Rejection Sensitivity":            ["positive feedback with one small note","cried in the bathroom over a note","one small criticism destroyed me"],
    "Hyperarousal":                     ["permanently set to high alert","even on holiday can't unwind","haven't slept deeply in years"],
    "Avoidance Behavior":               ["changed my entire commute","avoid passing the hospital","avoid anything that reminds me of her"],
    "Loneliness":                       ["profoundly alone","know no one here","no one actually knows","moved cities","cry every morning","full contact list","social media following and alone"],
    "Social Withdrawal":                ["used to host dinner parties","cancel every plan the morning of","cancel plans and feel relief then guilt"],
    "Conflict Avoidance":               ["watched manager take credit and said nothing","price of peace","stay silent to avoid conflict"],
    "Codependency":                     ["don't know where she ends and i begin","when she's anxious i become anxious"],
    "Attachment Anxiety":               ["didn't say i love you when we hung up","cataloguing every interaction","catalog every word for clues"],
    "Attachment Avoidance":             ["ghosted her for a week","every time someone gets close i pull back","can't let it happen"],
    "Boundary Difficulties":            ["called at 11pm and i answered","apologized for missing her message","answer calls at any hour"],
    "Communication Breakdown":          ["read it as aggressive","called me defensive","clear message completely misread"],
    "Family System Stress":             ["sunday dinners are a minefield","brother and father haven't spoken","tension sits on the whole family"],
    "Workplace Conflict":               ["reported me for something i didn't do","hr meetings weekly","dread monday mornings now"],
    "Romantic Relationship Distress":   ["exist parallel to each other","not sure i'm in love anymore","last real conversation was months ago"],
    "Grief and Loss":                   ["set two cups for tea in the morning","forgetting and then remembering","died six weeks ago and i still"],
    "Positive Reframing":               ["pain as a starting gun","redundancy pushed me to pursue","brutal but it opened a door"],
    "Gratitude":                        ["sat with me all night","someone showed up","that meant everything to me"],
    "Progress Acknowledgment":          ["walked through the main entrance","cried with relief at my own progress","six months ago couldn't and now i can"],
    "Motivation":                       ["waking up before my alarm","working toward something again","started waking before the alarm"],
    "Relief":                           ["legal case is settled","don't have to fight anymore","bracing against it for two years"],
    "Hope":                             ["thought about next year without flinching","made a plan and believed it","first time thought about future calmly"],
    "Mindfulness":                      ["noticed the trees","just walking","wasn't thinking about","walked and noticed","present without thinking"],
    "Social Connection":                ["coffee for two hours","needed to be heard","she just listened","felt heard","someone really listened"],
    "Self-Compassion":                  ["what i'd say to a friend in my situation","couldn't say it to myself","kind to a friend but not to me"],
    "Resilience":                       ["still here","still functioning","didn't know i was capable","lost a job","survived all of it","i'm still here after"],
    "Acceptance":                       ["stopped fighting the fact of it","energy going into adaptation now","denial turned into adaptation"],
    "Empowerment":                      ["said no to a project","choose what i give my energy to","first time i chose"],
    "Insight/Breakthrough":             ["recreating my mother's disapproval","realized in session today","uncomfortable to see but now clear"],
    "Post-Traumatic Growth":            ["used to resent what happened","wouldn't trade the person i've become","made me more empathetic deliberate"],
    "Sleep Disturbance":                ["wake at 3am with mind racing","lie there for two hours","fall asleep fine then wake early"],
    "Appetite Change":                  ["eat because i know i need to","small portions rarely hungry","food stopped being enjoyable"],
    "Fatigue/Burnout":                  ["came back just as depleted","rest didn't touch what's empty","holiday didn't help exhaustion"],
    "Chronic Pain-Linked Depression":   ["fibromyalgia","used to run used to cook","can barely do either now"],
    "Substance Use Risk":               ["one glass became a bottle","how i start the day now","wine to wind down became dependency"],
    "Self-Harm Risk":                   ["dig my nails in until it hurts","interrupts the noise","nails in until pain"],
    "Psychosomatic Symptoms":           ["stomach seizes up before","body doesn't know the difference between","difficult conversation stomach reacts"],
    "Suicidal Crisis (Immediate)":      ["pills in my hand","in my car right now with","not sure i want to be talked out of this"],
}
